### ISSUE TITLE
Make the breaks better

### ISSUE THREAD

**Issue by jpsalado92** [jouni-kantola/mobtimer#15]
My suggestion is to stop treating breaks as a mob participant. Instead, breaks should happen in a bigger interval (f.e. 1h) after the mob was firstly set.

**Comment by jouni-kantola** [comment]
@jpsalado92 Break starts automatically in the merged PR after last member in the cycle. I thought it could be a driver for people taking breaks. What do you think?

**Comment by jpsalado92** [comment]
I think I have seen some strange behaviour with the breaks, will update you
if I find that again.

**Comment by jpsalado92** [comment]
Hello Jouni! Some feedback about the timer.

The strange behaviour I mentioned was intended behaviour I think, but it's something a little bit misleading for first users. 
Basically, when a round ends and the break starts, having an actionable button that says "Take a Break!" is a little bit confusing in my opinion. The first time I had that break I didnt even understand if I was in a break due to that button (as, if I was on a break, why is there a button that encourages me to take a break?). Now I understand that the button actually hides the window, but it was not that clear to me in the first time.

**Comment by jouni-kantola** [comment]
Thanks for the feedback. This was partly what I was thinking could be weird UX when the breaks were automatic but everything else were triggered by an interaction. 

I think the automatic breaks are beneficial from many perspectives, e.g. recovery, but the experience when switching over to break should be clarified.

**Comment by jouni-kantola** [comment]
In [version 2.5.0](https://github.com/jouni-kantola/mobtimer/releases/tag/v2.5.0) information about break is displayed like this instead of reusing buttons for information:
![image](https://github.com/jouni-kantola/mobtimer/assets/2670127/ef20aa43-7a4a-4fc0-806a-d8893633d74a)
What do you think about this update, @jpsalado92?

**Comment by jpsalado92** [comment]
Hello @jouni-kantola,

Looks good! At least the way it is right now there is no confusion to me, so thanks for the change. Also, even if the looks of the app didn't change that much I see how busy you kept yourself with the source code so good work!

It would be cool if I could throw feedback while experimenting with it in a mob scenario, but I still haven't started my new job and I miss a team to test it with. In any case, here are some ideas:

1. There is one annoying scenario while using the app, that is, when you want to do stuff in the computer without using the app, one would "minimize" it with the button next to the cross mark on the top-right corner right? Not having the "minimize" button gets me shrinking the app layout and dragging it to one corner of my screen, which is a little unpleasant. Note that this is not such a big thing, but still, would cause "friction" while using the app.
2. The dark theme looks good to me, nice!
3. I would rearrange the Take Breaks button. I attached two different options I believe would make it better.
(Note that I'm not that pro at UI/UX, so maybe there is a reason for it to be there that I'm not aware of, if that's the case just ignore this request.)
    - **Option 1:** Under the listed members. This could be a good idea as the "break" is a direct continuation of the list of members iterations.
![image](https://github.com/jouni-kantola/mobtimer/assets/26083931/1ae727e5-d880-42fd-acb8-efaa85ee34f9)
    - **Option 2:** Just before the listed members. This could be a good idea as it is a config setting that might belong more closely to the control buttons.
![image](https://github.com/jouni-kantola/mobtimer/assets/26083931/4a3f2148-9a0d-4795-b4ea-14a33060f7dc)
 
Let me know if you need any clarifications 😸 

JPS

**Comment by jouni-kantola** [comment]
Glad to hear you liked the changes.

Thank you very much for your feedback! I'll create separate issues for them and link them here.
