### ISSUE TITLE
Move break toggle 

### ISSUE THREAD

**Issue by jouni-kantola** [jouni-kantola/mobtimer#45]
The current position of the break toggle next to the timer is to keep settings together.

An idea from @jpsalado92 was to move the break toggle. This discussion started here:
https://github.com/jouni-kantola/mobtimer/issues/15#issuecomment-1672788566

To not mix too many things topics into the same issue this specific topic can be moved here.

Screenshots from old issue:
![break-toggle-under-team](https://github.com/jouni-kantola/mobtimer/assets/2670127/efd6c473-eb08-4980-8295-503823bbe008)
![break-toggle-over-team](https://github.com/jouni-kantola/mobtimer/assets/2670127/2d93843f-008d-46af-8074-ee50db950310)

**Comment by jouni-kantola** [comment]
I think I prefer the option 2, with the break toggle above the team.

**Comment by jouni-kantola** [comment]
@jpsalado92: In [v2.7.0](https://github.com/jouni-kantola/mobtimer/releases/tag/v2.7.0) the breaks toggle is moved to a team options section, in line with your suggestion. Thank you! 🥇  Let me know if you come up with any other improvement ideas.

**Comment by jpsalado92** [comment]
It looks quite nice, good job with that Jouni!

I wish my current team did some mob programming to provide more feedback
for the tool, but will let you know if I come up with anything.
