### ISSUE TITLE
Active/Inactive status gets misaligned when shuffling

### ISSUE THREAD

**Issue by helenaryman** [jouni-kantola/mobtimer#70]

**Comment by jouni-kantola** [comment]
Thanks for reporting, @helenaryman! There's definitely something off with how the shuffle affects the app.

In the attached screenshot a shuffled team displays an away member as current driver (active). This should be an invalid state.
![away-shown-as-active-bug](https://github.com/jouni-kantola/mobtimer/assets/2670127/40ec7bfd-b637-44fb-bc8f-70fcee9fc437)

**Comment by jouni-kantola** [comment]
This has now been fixed in [v2.7.1](https://github.com/jouni-kantola/mobtimer/releases/tag/v2.7.1). Thank you for highlighting the issue, @helenaryman! 🥇
