### ISSUE TITLE
Separate icon path for tray in development

### ISSUE THREAD

**Issue by jqtmviyu** [jouni-kantola/mobtimer#73]
I also encountered problems with the setting of the tray icon on Intel macos 12.7.

After testing, different paths can be solved by detecting vite development environment variables.

In this way, you don't need to building before running.

Maybe it's a better way for neutralino to put the tray icon path into `neutralino.config.json`.

e.g
```ts
  const iconpath = import.meta.env.DEV ? '/resources/public/trayIcon.png' : '/dist/trayIcon.png'
  let tray = {
    icon: iconpath,
    menuItems: [{ id: 'QUIT', text: 'Quit' }],
  }
```

**Comment by jouni-kantola** [comment]
@jqtmviyu Thank you for reaching out. I think this issue fits better to be reported to [Neutralinojs](https://github.com/neutralinojs/neutralinojs/issues). If I'm not misunderstanding, it's flexibility in the underlying framework you're looking for. What do you think?

**Comment by jouni-kantola** [comment]
Sorry, I read your issue again. I now understand this as you're missing the tray icon until you've built the app the first time. Is that correct? 

If yes, do you feel comfortable doing a pull request or would you prefer if I test your suggested solution?

**Comment by jqtmviyu** [comment]
> Sorry, I read your issue again. I now understand this as you're missing the tray icon until you've built the app the first time. Is that correct?
> 
> If yes, do you feel comfortable doing a pull request or would you prefer if I test your suggested solution?

Sorry, English is not my native language, so I'm using Bing Translate, and the expression may not be very clear.

I found your issue regarding tray crash while searching for it, [here](https://github.com/jouni-kantola/mobtimer/issues/29#issue-1792476565). You fixed this issue through this commit: [here](https://github.com/jouni-kantola/mobtimer/commit/ae947371e36e919ba1e37eb58eccbf1f6d137877).

It's also mentioned in the readme that we need to execute build before start.

I think this might be because neu build does not handle tray icon paths well during packaging.

However, we can elegantly handle this issue through vite's environment variables, without the need to build before executing start.

Of course, a better approach might be to improve Neutralinojs's handling of tray icon paths, but this issue may have persisted for a long time. I'm pessimistic about it, so patching it in this way might be the only option.

**Comment by jouni-kantola** [comment]
Thank you for clarifying, I appreciate it. 💡

I think your idea sounds very good. Do you want to make a pull request? If yes, then please also remove the README instruction about `npm run build` in [Getting started](https://github.com/jouni-kantola/mobtimer?tab=readme-ov-file#getting-started).

**Comment by jqtmviyu** [comment]
I'm too lazy to fork the warehouse to submit pr. 😇

Just edit this:  `neutralino-api.ts` line: 26

```ts
    await os.setTray({
        icon: import.meta.env.DEV ? "/resources/public/trayIcon.png" : "/dist/trayIcon.png",
```

have a try.
