### ISSUE TITLE
As a Windows user, I want to be able to download the app with no security warnings

### ISSUE THREAD

**Issue by jpsalado92** [jouni-kantola/mobtimer#79]
Hi @jouni-kantola, have some new feedback for you:

I get multiple malware notifications when downloading the release .zip file.

- The first one I get is from chrome itself.
- The second one I get is from Windows.

I can always "continue at my own risk", so its not as if the app will not run, but still, **if you are a new user to the project, you might run away due to these things.**

Let me know if you need more info around these.

**Comment by jouni-kantola** [comment]
I honestly don't know if this can be solved without publishing releases to the Windows store or to a package registry. If you clone the repository and start the app there are no warnings. 

Do you have any ideas?

**Comment by jpsalado92** [comment]
Buff, not really. I guess it might not be worth the effort, but I posted it
in case you didnt know.
